//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BanBif.SDP.DA
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class panelEntities : DbContext
    {
        public panelEntities()
            : base("name=panelEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<SDP_Log> SDP_Log { get; set; }
        public virtual DbSet<SDP_Plazo> SDP_Plazo { get; set; }
        public virtual DbSet<SDP_Registros> SDP_Registros { get; set; }
        public virtual DbSet<SDP_Tarifario> SDP_Tarifario { get; set; }
        public virtual DbSet<SDP_TarifarioDolares> SDP_TarifarioDolares { get; set; }
    
        public virtual ObjectResult<SDP_ConsultaMatrizTarifas_Result> SDP_ConsultaMatrizTarifas()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SDP_ConsultaMatrizTarifas_Result>("SDP_ConsultaMatrizTarifas");
        }
    
        public virtual ObjectResult<SDP_ConsultaPlazos_Result> SDP_ConsultaPlazos()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SDP_ConsultaPlazos_Result>("SDP_ConsultaPlazos");
        }
    
        public virtual int SDP_RegistrarSimulacionCliente(string dni, string mail, Nullable<decimal> monto, string moneda, Nullable<int> plazo, Nullable<decimal> tasa, Nullable<decimal> interes, Nullable<int> tdatos)
        {
            var dniParameter = dni != null ?
                new ObjectParameter("dni", dni) :
                new ObjectParameter("dni", typeof(string));
    
            var mailParameter = mail != null ?
                new ObjectParameter("mail", mail) :
                new ObjectParameter("mail", typeof(string));
    
            var montoParameter = monto.HasValue ?
                new ObjectParameter("monto", monto) :
                new ObjectParameter("monto", typeof(decimal));
    
            var monedaParameter = moneda != null ?
                new ObjectParameter("moneda", moneda) :
                new ObjectParameter("moneda", typeof(string));
    
            var plazoParameter = plazo.HasValue ?
                new ObjectParameter("plazo", plazo) :
                new ObjectParameter("plazo", typeof(int));
    
            var tasaParameter = tasa.HasValue ?
                new ObjectParameter("tasa", tasa) :
                new ObjectParameter("tasa", typeof(decimal));
    
            var interesParameter = interes.HasValue ?
                new ObjectParameter("interes", interes) :
                new ObjectParameter("interes", typeof(decimal));
    
            var tdatosParameter = tdatos.HasValue ?
                new ObjectParameter("Tdatos", tdatos) :
                new ObjectParameter("Tdatos", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SDP_RegistrarSimulacionCliente", dniParameter, mailParameter, montoParameter, monedaParameter, plazoParameter, tasaParameter, interesParameter, tdatosParameter);
        }
    
        public virtual ObjectResult<SDP_ConsultaMatrizTarifasDolares_Result> SDP_ConsultaMatrizTarifasDolares()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SDP_ConsultaMatrizTarifasDolares_Result>("SDP_ConsultaMatrizTarifasDolares");
        }
    
        public virtual int SDP_RegistrarLog(string dni, Nullable<int> idregistro, Nullable<int> paso, string detalle)
        {
            var dniParameter = dni != null ?
                new ObjectParameter("dni", dni) :
                new ObjectParameter("dni", typeof(string));
    
            var idregistroParameter = idregistro.HasValue ?
                new ObjectParameter("idregistro", idregistro) :
                new ObjectParameter("idregistro", typeof(int));
    
            var pasoParameter = paso.HasValue ?
                new ObjectParameter("paso", paso) :
                new ObjectParameter("paso", typeof(int));
    
            var detalleParameter = detalle != null ?
                new ObjectParameter("detalle", detalle) :
                new ObjectParameter("detalle", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SDP_RegistrarLog", dniParameter, idregistroParameter, pasoParameter, detalleParameter);
        }
    }
}
