//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BanBif.SDP.DA
{
    using System;
    using System.Collections.Generic;
    
    public partial class SDP_Tarifario
    {
        public int id { get; set; }
        public Nullable<int> plazo { get; set; }
        public Nullable<decimal> r1ka20k { get; set; }
        public Nullable<decimal> r20ka30k { get; set; }
        public Nullable<decimal> r30ka85k { get; set; }
        public Nullable<decimal> r85ka100k { get; set; }
        public Nullable<decimal> r100k { get; set; }
        public Nullable<int> estado { get; set; }
    }
}
