//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BanBif.SDP.DA
{
    using System;
    using System.Collections.Generic;
    
    public partial class SDP_Log
    {
        public int id { get; set; }
        public Nullable<int> idregistro { get; set; }
        public string dni { get; set; }
        public Nullable<int> paso { get; set; }
        public string detalle { get; set; }
        public Nullable<System.DateTime> fecha { get; set; }
    }
}
