//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BanBif.SDP.DA
{
    using System;
    using System.Collections.Generic;
    
    public partial class SDP_Registros
    {
        public int registroid { get; set; }
        public string dni { get; set; }
        public Nullable<decimal> monto { get; set; }
        public string moneda { get; set; }
        public Nullable<int> plazo { get; set; }
        public Nullable<decimal> tasa { get; set; }
        public Nullable<decimal> interes { get; set; }
        public Nullable<System.DateTime> fecha { get; set; }
        public Nullable<int> Tdatos { get; set; }
        public string mail { get; set; }
    }
}
