//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BanBif.SDP.DA
{
    using System;
    using System.Collections.Generic;
    
    public partial class SDP_TarifarioDolares
    {
        public int id { get; set; }
        public Nullable<int> plazo { get; set; }
        public Nullable<decimal> r1 { get; set; }
        public Nullable<decimal> r2 { get; set; }
        public Nullable<decimal> r3 { get; set; }
        public Nullable<decimal> r4 { get; set; }
        public Nullable<int> estado { get; set; }
    }
}
